### ISSUE TITLE
Pulls inconsistently failing

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#34] opened 2020-11-06 20:15 UTC
I've been pulling a large number of Miami addresses through location.get_detail using the rate_limiter option in the package initialization. On test batches of addresses (5-10K), I find that a significant number (~20%) will return as invalid IDs in the CSV file. The weird things are...

1. On spot checks, I can pull any of these failed addresses just fine either through the API one-by-one or looking them up on the Flood Factor website
2. To test whether this was something with the ordering or the rate limit, I tried changing the ordering and going slower, but the same properties returned as invalid IDs. 
3. However, when I then selected only these invalid IDs and ran them through again, about 80% of them returned as valid! I ran through the remaining 20% invalid again, and 80% came back valid 

At the bottom you will find my code snippet. Happy to pass along a sample of addresses to see if you get the same behavior (it looks like I can't attached CSVs here). I'm running Python 3.7.9 on Jupyter Notebook, Windows 10. I just updated to the latest API access this afternoon (i.e. pip install --upgrade fsf_api_access_python) 

I appreciate any help you can offer. Thank you!

Snippet: 
import shapely.geometry
import nest_asyncio
nest_asyncio.apply()
import numpy as np
import pandas as pd
import requests
import json
import os
import csv
from csv import DictReader
import firststreet
fs = firststreet.FirstStreet("api_key",rate_limit=4000,rate_period=62)
pull_address = "filename.csv"
fs.location.get_detail(pull_address,'property',csv=True)

**Comment by Lyetenth** [comment] 2020-11-06 20:23
Hey @mulderphilip,

That definitely sounds weird and I can take a look for you. Are you able to drop the sample address file into a google drive?

(Also please make sure to keep the API key secure!)

**Comment by mulderphilip** [comment] 2020-11-06 20:25
Rookie mistake, sorry! Happy to share the files, let me know

**Comment by Lyetenth** [comment] 2020-11-06 20:29
@mulderphilip, I've open up a temporary google drive folder, if you could throw the file in there

https://drive.google.com/drive/u/1/folders/1Ygd3fRxXY-UlcAVrJ211Q6G1aA6xmPfA

**Comment by mulderphilip** [comment] 2020-11-06 20:31
Got it, should be uploaded. Thank you!

**Comment by Lyetenth** [comment] 2020-11-10 17:07
Hey @mulderphilip ,

I've taken a look and it might take a bit longer to identify the root issue. It looks like when too many consecutive address calls are made, the server returns an error (leading to the invalid ID tag since the response is an error)

Some temporary solutions while we investigate this:
1. I have not noticed the issue for FSIDs or lat/lngs, so those two input types may work better if you have them instead of addresses

2. Slow down your rate_period while keeping the same ratio. ie: Instead of `rate_limit=4000, rate_period=62`, try `rate_limit=65, rate_period=1, connection_limit=10`. The issue is too many consecutive calls, so slowing down the rate to smaller chunks may alleviate the issues. This will be a bit slower than running the original ratio with a larger `connection_limit`, but from my test it seems to be the most stable (using the second configuration I only got 1 invalid fsid out of 4968 addresses). Feel free to try adjusting the parameters



We'll let you know when we get an update on the investigation

**Comment by mulderphilip** [comment] 2020-11-10 17:15
@Lyetenth , thanks so much! I'll try those fixes, I'm sure they'll work for the data I need.

**Comment by Lyetenth** [comment] 2020-11-24 15:42
Hey @mulderphilip ,

We've identified the issue being the service we use to convert and identify addresses in the API's backend. Unfortunately at the moment, the service limits us to 1000 calls per minute. I'm told there are plans on changing this some time in the future, but for now the two temporary solutions above will have to do.

ie: 
1. Using an FSID or lat/lngs instead of an address since those two methods don't use this service
2. Slowing down the rate to `rate_limit=1000, rate_period=60`. (Different configurations may still unexpectedly work)


Sorry for no concrete fix, we'll notify the Flood Lab members with API version updates. Thanks for helping us identify the issue!

**Comment by Lyetenth** [comment] 2021-01-21 19:24
Hey @mulderphilip,

We made some changes to the address matching and the problem should be fixed. Feel free to test it again and re-open this issue if the issue persists

**Closed as completed by Lyetenth** 2021-01-21 19:24 UTC
Labels: bug
